services:
  # =============================================================================
  # Redpanda broker (hostname: broker — internal Kafka API on broker:9092)
  # =============================================================================
  # Both broker overlays expose hostname=broker on internal port 9092.
  # Flink SQL 01_source.sql always uses 'broker:9092' — zero changes between brokers.
  broker:
    image: docker.redpanda.com/redpandadata/redpanda:v25.3.7
    container_name: template-redpanda
    hostname: broker
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 512M
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://broker:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://broker:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr broker:33145
      - --advertise-rpc-addr broker:33145
      - --mode dev-container
      - --default-log-level warn
    ports:
      - "19092:19092"   # External Kafka API (for local producers/consumers)
      - "18082:18082"   # HTTP Proxy
      - "9644:9644"     # Admin API
    healthcheck:
      # rpk v25+: --brokers flag removed from cluster health subcommand;
      # reads broker from node's own config. grep -E checks value=true, not just key presence.
      test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 20s
    networks:
      - pipeline-net

  # =============================================================================
  # Redpanda Console (web UI for topic inspection)
  # =============================================================================
  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v3.2.2
    container_name: template-redpanda-console
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console --config.filepath /tmp/config.yml'
    environment:
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["broker:9092"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://broker:9644"]
    ports:
      - "8085:8080"   # Redpanda Console web UI
    depends_on:
      broker:
        condition: service_healthy
    networks:
      - pipeline-net
