version: 2

sources:
  - name: raw_nyc_taxi
    description: "NYC TLC Yellow Taxi data - Hudi Silver table parquet files via DuckDB read_parquet"
    schema: main
    tables:
      - name: raw_yellow_trips
        description: "Silver-layer cleaned trips from Hudi (Spark-processed, read as parquet)"
        config:
          external_location: "read_parquet('s3://warehouse/silver/cleaned_trips/**/*.parquet')"
