name: 'de_pipeline'
version: '1.0.0'
config-version: 2

profile: 'de_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  de_pipeline:
    +schema: raw
    taxi_zone_lookup:
      +column_types:
        LocationID: INTEGER
        Borough: VARCHAR
        Zone: VARCHAR
        service_zone: VARCHAR
    payment_type_lookup:
      +column_types:
        payment_type_id: INTEGER
        payment_type_name: VARCHAR
    rate_code_lookup:
      +column_types:
        rate_code_id: INTEGER
        rate_code_name: VARCHAR
    vendor_lookup:
      +column_types:
        vendor_id: INTEGER
        vendor_name: VARCHAR
        vendor_abbr: VARCHAR

models:
  de_pipeline:
    +materialized: view
    staging:
      +materialized: view
      +schema: staging
      stg_yellow_trips:
        +materialized: table
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      core:
        +materialized: table
        +schema: marts
      analytics:
        +materialized: table
        +schema: marts
