name: nyc_taxi_pipeline_04
version: "1.0.0"
config-version: 2
profile: nyc_taxi_pipeline_04
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

dispatch:
  - macro_namespace: nyc_taxi_dbt
    search_order: [nyc_taxi_pipeline_04, nyc_taxi_dbt]

seeds:
  nyc_taxi_pipeline_04:
    +schema: raw

models:
  nyc_taxi_pipeline_04:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      core:
        +materialized: table
        +schema: marts
      analytics:
        +materialized: table
        +schema: marts
