nyc_taxi_pipeline_04:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /dbt/warehouse.duckdb
      extensions:
        - iceberg
        - httpfs
      settings:
        s3_region: us-east-1
        s3_endpoint: minio:9000
        s3_access_key_id: minioadmin
        s3_secret_access_key: minioadmin
        s3_use_ssl: false
        s3_url_style: path
      threads: 4
