version: 2

sources:
  - name: raw_nyc_taxi
    description: "NYC TLC Yellow Taxi data - Iceberg Silver table via Spark"
    schema: warehouse.silver
    tables:
      - name: raw_yellow_trips
        description: "Silver-layer cleaned trips from Iceberg (Spark-processed)"
        identifier: cleaned_trips
