version: 2

sources:
  - name: raw_nyc_taxi
    description: "NYC TLC Yellow Taxi data - Iceberg Silver table via DuckDB iceberg_scan"
    schema: main
    tables:
      - name: raw_yellow_trips
        description: "Silver-layer cleaned trips from Iceberg (stream-processed)"
        config:
          external_location: "iceberg_scan('s3://warehouse/silver/cleaned_trips', allow_moved_paths = true)"
