version: 2

sources:
  - name: raw_nyc_taxi
    description: "NYC TLC Yellow Taxi data - Iceberg Silver table via DuckDB iceberg_scan"
    schema: main
    tables:
      - name: raw_yellow_trips
        description: "Silver-layer quality-filtered trips from Iceberg (Spark-processed, original column names)"
        config:
          # Spark HadoopCatalog warehouse = s3a://warehouse/iceberg
          # Table warehouse.silver.cleaned_trips -> physical path s3://warehouse/iceberg/silver/cleaned_trips
          external_location: "iceberg_scan('s3://warehouse/iceberg/silver/cleaned_trips', allow_moved_paths = true)"
