version: 2

models:
  - name: stg_yellow_trips
    description: "Passthrough from RisingWave silver_cleaned_trips MV. Data is already cleaned, typed, and enriched."
    columns:
      - name: trip_id
        description: "Surrogate key (MD5 hash) generated in RisingWave MV"
        tests:
          - not_null
          - unique
      - name: vendor_id
        description: "TPEP provider: 1=Creative Mobile Technologies, 2=VeriFone Inc., 6=Unknown/Other"
        tests:
          - not_null
      - name: pickup_location_id
        description: "TLC Taxi Zone ID for pickup"
        tests:
          - not_null
          - relationships:
              to: ref('stg_taxi_zones')
              field: location_id
              config:
                severity: warn
      - name: dropoff_location_id
        description: "TLC Taxi Zone ID for dropoff"
        tests:
          - not_null
          - relationships:
              to: ref('stg_taxi_zones')
              field: location_id
              config:
                severity: warn
      - name: pickup_datetime
        tests:
          - not_null
      - name: dropoff_datetime
        tests:
          - not_null
      - name: trip_distance_miles
        tests:
          - not_null
      - name: fare_amount
        tests:
          - not_null
      - name: total_amount
        tests:
          - not_null

  - name: stg_taxi_zones
    description: "Taxi zone reference mapping location IDs to borough and zone names"
    columns:
      - name: location_id
        tests:
          - unique
          - not_null
      - name: borough
        tests:
          - not_null
      - name: zone_name
        tests:
          - not_null

  - name: stg_payment_types
    description: "Payment type reference"
    columns:
      - name: payment_type_id
        tests:
          - unique
          - not_null
      - name: payment_type_name
        tests:
          - not_null

  - name: stg_rate_codes
    description: "Rate code reference"
    columns:
      - name: rate_code_id
        tests:
          - unique
          - not_null
      - name: rate_code_name
        tests:
          - not_null
