# Pipeline 05: dbt-spark profile reading Silver Iceberg tables via Spark Thrift Server
#
# dbt-spark connects to Spark Thrift Server, which can natively read Iceberg tables
# written by Spark Structured Streaming. This avoids DuckDB version-hint compatibility issues.

nyc_taxi_pipeline_05:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      schema: default
      host: spark-thrift
      port: 10000
      user: dbt
      threads: 4
      connect_timeout: 60
      connect_retries: 5
