# Pipeline 05: dbt-duckdb reading Iceberg Silver tables from MinIO via iceberg_scan()
#
# Same pattern as P04 (Flink). Spark writes Iceberg to MinIO; DuckDB reads it
# directly via the iceberg extension — no Spark Thrift Server needed for dbt.
# The Spark Thrift Server service has been removed from docker-compose.yml.

nyc_taxi_pipeline_05:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /tmp/p05_dbt.duckdb
      schema: main
      threads: 4
      extensions:
        - httpfs
        - parquet
        - iceberg
      settings:
        memory_limit: "2GB"
        s3_endpoint: "minio:9000"
        s3_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID', 'minioadmin') }}"
        s3_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY', 'minioadmin') }}"
        s3_url_style: "path"
        s3_use_ssl: false
        s3_region: "us-east-1"
