version: 2

sources:
  - name: raw_nyc_taxi
    description: "NYC TLC Yellow Taxi data - Materialize materialized views"
    schema: public
    tables:
      - name: raw_yellow_trips
        description: "Silver-layer cleaned trips from Materialize MV"
        identifier: silver_cleaned_trips
