# =============================================================================
# dbt Profile for Pipeline 01: Kafka + Flink + Iceberg
# =============================================================================
# Uses DuckDB with iceberg and httpfs extensions to read Iceberg tables
# from MinIO (S3-compatible) object storage.
# =============================================================================

nyc_taxi_dbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /dbt/p01_dbt.duckdb
      schema: main
      threads: 4
      extensions:
        - httpfs
        - parquet
        - iceberg
      settings:
        memory_limit: "2GB"
        s3_endpoint: "minio:9000"
        s3_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID', 'minioadmin') }}"
        s3_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY', 'minioadmin') }}"
        s3_url_style: "path"
        s3_use_ssl: false
        s3_region: "us-east-1"
