version: 2

sources:
  - name: raw_nyc_taxi
    description: "NYC TLC Yellow Taxi data - Delta Lake Silver table via DuckDB delta_scan"
    meta:
      external_location: "s3://warehouse/silver/cleaned_trips"
    tables:
      - name: raw_yellow_trips
        description: "Silver-layer cleaned trips from Delta Lake (Spark-processed)"
        identifier: "delta_scan('s3://warehouse/silver/cleaned_trips')"
