version: 2

sources:
  - name: raw_nyc_taxi
    description: "NYC TLC Yellow Taxi data - Delta Lake Silver table via DuckDB read_parquet"
    schema: main
    tables:
      - name: raw_yellow_trips
        description: "Silver-layer cleaned trips from Delta Lake (Spark-processed, snake_case columns)"
        config:
          # Spark writes Delta Lake parquet files to s3://warehouse/silver/cleaned_trips/
          # DuckDB's httpfs reads them directly via read_parquet glob.
          # delta_scan() requires EC2-style credential discovery that fails in Docker;
          # read_parquet via httpfs uses the s3_* settings in profiles.yml correctly.
          external_location: "read_parquet('s3://warehouse/silver/cleaned_trips/*.snappy.parquet')"
