name: 'nyc_taxi_pipeline_22'
version: '1.0.0'
config-version: 2

profile: 'pipeline_22'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  nyc_taxi_pipeline_22:
    +schema: main

models:
  nyc_taxi_pipeline_22:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      core:
        +materialized: table
      analytics:
        +materialized: table
