version: 2

sources:
  - name: raw_nyc_taxi
    description: "NYC TLC Yellow Taxi data - Iceberg Bronze table via DuckDB iceberg_scan"
    schema: main
    tables:
      - name: raw_yellow_trips
        description: "Bronze-layer raw trips from Iceberg (Flink-processed, original column names)"
        config:
          external_location: "iceberg_scan('s3://warehouse/bronze/raw_trips', allow_moved_paths = true)"
